/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const TournamentStatus = IDL.Variant({
  'closed' : IDL.Null,
  'upcoming' : IDL.Null,
  'completed' : IDL.Null,
  'ongoing' : IDL.Null,
});
export const Tournament = IDL.Record({
  'id' : IDL.Text,
  'map' : IDL.Text,
  'status' : TournamentStatus,
  'qrCodeBlob' : IDL.Opt(ExternalBlob),
  'name' : IDL.Text,
  'roomPassword' : IDL.Opt(IDL.Text),
  'totalSlots' : IDL.Nat,
  'upiId' : IDL.Text,
  'entryFee' : IDL.Nat,
  'roomId' : IDL.Opt(IDL.Text),
  'filledSlots' : IDL.Nat,
  'dateTime' : Time,
  'matchRules' : IDL.Text,
  'prizePool' : IDL.Nat,
});
export const TicketStatus = IDL.Variant({
  'closed' : IDL.Null,
  'open' : IDL.Null,
  'replied' : IDL.Null,
});
export const SupportTicket = IDL.Record({
  'status' : TicketStatus,
  'adminReply' : IDL.Opt(IDL.Text),
  'subject' : IDL.Text,
  'playerId' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'ticketId' : IDL.Text,
  'repliedAt' : IDL.Opt(Time),
  'playerName' : IDL.Text,
  'screenshotBlob' : IDL.Opt(ExternalBlob),
});
export const SocialLinks = IDL.Record({
  'instagram' : IDL.Text,
  'youtube' : IDL.Text,
  'telegram' : IDL.Text,
});
export const TermsAndConditions = IDL.Record({ 'content' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'createSupportTicket' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [IDL.Text],
      [],
    ),
  'createTournament' : IDL.Func(
      [IDL.Text, Time, IDL.Nat, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'findUnusedSlots' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
  'generateOtp' : IDL.Func([], [IDL.Text], []),
  'getAllSupportTicketsSorted' : IDL.Func(
      [],
      [IDL.Vec(SupportTicket)],
      ['query'],
    ),
  'getSocialLinks' : IDL.Func([], [SocialLinks], ['query']),
  'getTermsAndConditions' : IDL.Func([], [TermsAndConditions], ['query']),
  'getTournamentsByMap' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Tournament)],
      ['query'],
    ),
  'registerForTournament' : IDL.Func([IDL.Text, ExternalBlob], [IDL.Text], []),
  'registerPlayer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'searchSupportTicketsByPlayerName' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SupportTicket)],
      ['query'],
    ),
  'updateSocialLinks' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateTermsAndConditions' : IDL.Func([IDL.Text], [], []),
  'verifyOtp' : IDL.Func([IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const TournamentStatus = IDL.Variant({
    'closed' : IDL.Null,
    'upcoming' : IDL.Null,
    'completed' : IDL.Null,
    'ongoing' : IDL.Null,
  });
  const Tournament = IDL.Record({
    'id' : IDL.Text,
    'map' : IDL.Text,
    'status' : TournamentStatus,
    'qrCodeBlob' : IDL.Opt(ExternalBlob),
    'name' : IDL.Text,
    'roomPassword' : IDL.Opt(IDL.Text),
    'totalSlots' : IDL.Nat,
    'upiId' : IDL.Text,
    'entryFee' : IDL.Nat,
    'roomId' : IDL.Opt(IDL.Text),
    'filledSlots' : IDL.Nat,
    'dateTime' : Time,
    'matchRules' : IDL.Text,
    'prizePool' : IDL.Nat,
  });
  const TicketStatus = IDL.Variant({
    'closed' : IDL.Null,
    'open' : IDL.Null,
    'replied' : IDL.Null,
  });
  const SupportTicket = IDL.Record({
    'status' : TicketStatus,
    'adminReply' : IDL.Opt(IDL.Text),
    'subject' : IDL.Text,
    'playerId' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'ticketId' : IDL.Text,
    'repliedAt' : IDL.Opt(Time),
    'playerName' : IDL.Text,
    'screenshotBlob' : IDL.Opt(ExternalBlob),
  });
  const SocialLinks = IDL.Record({
    'instagram' : IDL.Text,
    'youtube' : IDL.Text,
    'telegram' : IDL.Text,
  });
  const TermsAndConditions = IDL.Record({ 'content' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'createSupportTicket' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [IDL.Text],
        [],
      ),
    'createTournament' : IDL.Func(
        [
          IDL.Text,
          Time,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Text],
        [],
      ),
    'findUnusedSlots' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
    'generateOtp' : IDL.Func([], [IDL.Text], []),
    'getAllSupportTicketsSorted' : IDL.Func(
        [],
        [IDL.Vec(SupportTicket)],
        ['query'],
      ),
    'getSocialLinks' : IDL.Func([], [SocialLinks], ['query']),
    'getTermsAndConditions' : IDL.Func([], [TermsAndConditions], ['query']),
    'getTournamentsByMap' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Tournament)],
        ['query'],
      ),
    'registerForTournament' : IDL.Func(
        [IDL.Text, ExternalBlob],
        [IDL.Text],
        [],
      ),
    'registerPlayer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'searchSupportTicketsByPlayerName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SupportTicket)],
        ['query'],
      ),
    'updateSocialLinks' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateTermsAndConditions' : IDL.Func([IDL.Text], [], []),
    'verifyOtp' : IDL.Func([IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };