/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const TournamentStatus = IDL.Variant({
  'closed' : IDL.Null,
  'upcoming' : IDL.Null,
  'completed' : IDL.Null,
  'ongoing' : IDL.Null,
});
export const Tournament = IDL.Record({
  'id' : IDL.Text,
  'map' : IDL.Text,
  'status' : TournamentStatus,
  'qrCodeBlob' : IDL.Opt(ExternalBlob),
  'name' : IDL.Text,
  'roomPassword' : IDL.Opt(IDL.Text),
  'totalSlots' : IDL.Nat,
  'upiId' : IDL.Text,
  'entryFee' : IDL.Nat,
  'roomId' : IDL.Opt(IDL.Text),
  'filledSlots' : IDL.Nat,
  'dateTime' : Time,
  'matchRules' : IDL.Text,
  'prizePool' : IDL.Nat,
});
export const PaymentProofStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const PaymentProof = IDL.Record({
  'transactionRef' : IDL.Text,
  'status' : PaymentProofStatus,
  'userId' : IDL.Text,
  'imageBase64' : IDL.Text,
  'timestamp' : Time,
  'amount' : IDL.Nat,
  'proofId' : IDL.Text,
});
export const Player = IDL.Record({
  'principal' : IDL.Principal,
  'displayName' : IDL.Text,
  'bgmiPlayerId' : IDL.Text,
  'mobile' : IDL.Text,
});
export const TicketStatus = IDL.Variant({
  'closed' : IDL.Null,
  'open' : IDL.Null,
  'replied' : IDL.Null,
});
export const SupportTicket = IDL.Record({
  'status' : TicketStatus,
  'adminReply' : IDL.Opt(IDL.Text),
  'subject' : IDL.Text,
  'playerId' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'ticketId' : IDL.Text,
  'repliedAt' : IDL.Opt(Time),
  'playerName' : IDL.Text,
  'screenshotBlob' : IDL.Opt(ExternalBlob),
});
export const VerifiedUserProfile = IDL.Record({
  'id' : IDL.Text,
  'coinWallet' : IDL.Nat,
  'displayName' : IDL.Text,
  'bgmiPlayerId' : IDL.Text,
  'mobile' : IDL.Text,
});
export const WithdrawalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
  'processed' : IDL.Null,
});
export const WithdrawalRequest = IDL.Record({
  'status' : WithdrawalStatus,
  'requestId' : IDL.Text,
  'userId' : IDL.Text,
  'timestamp' : Time,
  'upiId' : IDL.Text,
  'amount' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'bgmiPlayerId' : IDL.Text,
  'mobile' : IDL.Text,
});
export const RegistrationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const TournamentRegistration = IDL.Record({
  'status' : RegistrationStatus,
  'paymentScreenshotBlob' : ExternalBlob,
  'playerId' : IDL.Text,
  'registrationId' : IDL.Text,
  'tournamentId' : IDL.Text,
});
export const SocialLinks = IDL.Record({
  'instagram' : IDL.Text,
  'youtube' : IDL.Text,
  'telegram' : IDL.Text,
});
export const TermsAndConditions = IDL.Record({ 'content' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCoins' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'addPrizeCoins' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'approvePaymentProof' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'closeSupportTicket' : IDL.Func([IDL.Text], [], []),
  'createSupportTicket' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [IDL.Text],
      [],
    ),
  'createTournament' : IDL.Func(
      [IDL.Text, Time, IDL.Nat, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deductCoins' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'distributePrizeCoins' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'findUnusedSlots' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
  'generateOtp' : IDL.Func([], [IDL.Text], []),
  'getAdminPrincipal' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
  'getAllPaymentProofs' : IDL.Func([], [IDL.Vec(PaymentProof)], ['query']),
  'getAllPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
  'getAllSupportTicketsSorted' : IDL.Func(
      [],
      [IDL.Vec(SupportTicket)],
      ['query'],
    ),
  'getAllTournaments' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
  'getAllVerifiedUsers' : IDL.Func(
      [],
      [IDL.Vec(VerifiedUserProfile)],
      ['query'],
    ),
  'getAllWithdrawalRequests' : IDL.Func(
      [],
      [IDL.Vec(WithdrawalRequest)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDomainName' : IDL.Func([], [IDL.Text], ['query']),
  'getMyPaymentProofs' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PaymentProof)],
      ['query'],
    ),
  'getMyRegistrations' : IDL.Func(
      [],
      [IDL.Vec(TournamentRegistration)],
      ['query'],
    ),
  'getMySupportTickets' : IDL.Func([], [IDL.Vec(SupportTicket)], ['query']),
  'getMyUserId' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getMyWithdrawalRequests' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(WithdrawalRequest)],
      ['query'],
    ),
  'getRegistrationsForTournament' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(TournamentRegistration)],
      ['query'],
    ),
  'getSocialLinks' : IDL.Func([], [SocialLinks], ['query']),
  'getTermsAndConditions' : IDL.Func([], [TermsAndConditions], ['query']),
  'getTournamentById' : IDL.Func([IDL.Text], [IDL.Opt(Tournament)], ['query']),
  'getTournamentsByMap' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Tournament)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserWalletBalance' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getWalletBalance' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'isAdminPrincipal' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markWithdrawalRequestProcessed' : IDL.Func([IDL.Text], [], []),
  'registerAdminPrincipal' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'registerForTournament' : IDL.Func(
      [IDL.Text, IDL.Text, ExternalBlob],
      [IDL.Text],
      [],
    ),
  'registerForTournamentWithCoins' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'registerPlayer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'rejectPaymentProof' : IDL.Func([IDL.Text], [], []),
  'rejectWithdrawalRequest' : IDL.Func([IDL.Text], [], []),
  'replyToSupportTicket' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchSupportTicketsByPlayerName' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SupportTicket)],
      ['query'],
    ),
  'setDomainName' : IDL.Func([IDL.Text], [], []),
  'submitPaymentProof' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'submitWithdrawalRequest' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Text],
      [],
    ),
  'updateRegistrationStatus' : IDL.Func([IDL.Text, RegistrationStatus], [], []),
  'updateSocialLinks' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateTermsAndConditions' : IDL.Func([IDL.Text], [], []),
  'updateTournamentQrCode' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  'updateTournamentRoomDetails' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateTournamentStatus' : IDL.Func([IDL.Text, TournamentStatus], [], []),
  'verifyOtp' : IDL.Func([IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const TournamentStatus = IDL.Variant({
    'closed' : IDL.Null,
    'upcoming' : IDL.Null,
    'completed' : IDL.Null,
    'ongoing' : IDL.Null,
  });
  const Tournament = IDL.Record({
    'id' : IDL.Text,
    'map' : IDL.Text,
    'status' : TournamentStatus,
    'qrCodeBlob' : IDL.Opt(ExternalBlob),
    'name' : IDL.Text,
    'roomPassword' : IDL.Opt(IDL.Text),
    'totalSlots' : IDL.Nat,
    'upiId' : IDL.Text,
    'entryFee' : IDL.Nat,
    'roomId' : IDL.Opt(IDL.Text),
    'filledSlots' : IDL.Nat,
    'dateTime' : Time,
    'matchRules' : IDL.Text,
    'prizePool' : IDL.Nat,
  });
  const PaymentProofStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const PaymentProof = IDL.Record({
    'transactionRef' : IDL.Text,
    'status' : PaymentProofStatus,
    'userId' : IDL.Text,
    'imageBase64' : IDL.Text,
    'timestamp' : Time,
    'amount' : IDL.Nat,
    'proofId' : IDL.Text,
  });
  const Player = IDL.Record({
    'principal' : IDL.Principal,
    'displayName' : IDL.Text,
    'bgmiPlayerId' : IDL.Text,
    'mobile' : IDL.Text,
  });
  const TicketStatus = IDL.Variant({
    'closed' : IDL.Null,
    'open' : IDL.Null,
    'replied' : IDL.Null,
  });
  const SupportTicket = IDL.Record({
    'status' : TicketStatus,
    'adminReply' : IDL.Opt(IDL.Text),
    'subject' : IDL.Text,
    'playerId' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'ticketId' : IDL.Text,
    'repliedAt' : IDL.Opt(Time),
    'playerName' : IDL.Text,
    'screenshotBlob' : IDL.Opt(ExternalBlob),
  });
  const VerifiedUserProfile = IDL.Record({
    'id' : IDL.Text,
    'coinWallet' : IDL.Nat,
    'displayName' : IDL.Text,
    'bgmiPlayerId' : IDL.Text,
    'mobile' : IDL.Text,
  });
  const WithdrawalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'processed' : IDL.Null,
  });
  const WithdrawalRequest = IDL.Record({
    'status' : WithdrawalStatus,
    'requestId' : IDL.Text,
    'userId' : IDL.Text,
    'timestamp' : Time,
    'upiId' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'bgmiPlayerId' : IDL.Text,
    'mobile' : IDL.Text,
  });
  const RegistrationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const TournamentRegistration = IDL.Record({
    'status' : RegistrationStatus,
    'paymentScreenshotBlob' : ExternalBlob,
    'playerId' : IDL.Text,
    'registrationId' : IDL.Text,
    'tournamentId' : IDL.Text,
  });
  const SocialLinks = IDL.Record({
    'instagram' : IDL.Text,
    'youtube' : IDL.Text,
    'telegram' : IDL.Text,
  });
  const TermsAndConditions = IDL.Record({ 'content' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCoins' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'addPrizeCoins' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'approvePaymentProof' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'closeSupportTicket' : IDL.Func([IDL.Text], [], []),
    'createSupportTicket' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [IDL.Text],
        [],
      ),
    'createTournament' : IDL.Func(
        [
          IDL.Text,
          Time,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Text],
        [],
      ),
    'deductCoins' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'distributePrizeCoins' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'findUnusedSlots' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
    'generateOtp' : IDL.Func([], [IDL.Text], []),
    'getAdminPrincipal' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
    'getAllPaymentProofs' : IDL.Func([], [IDL.Vec(PaymentProof)], ['query']),
    'getAllPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
    'getAllSupportTicketsSorted' : IDL.Func(
        [],
        [IDL.Vec(SupportTicket)],
        ['query'],
      ),
    'getAllTournaments' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
    'getAllVerifiedUsers' : IDL.Func(
        [],
        [IDL.Vec(VerifiedUserProfile)],
        ['query'],
      ),
    'getAllWithdrawalRequests' : IDL.Func(
        [],
        [IDL.Vec(WithdrawalRequest)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDomainName' : IDL.Func([], [IDL.Text], ['query']),
    'getMyPaymentProofs' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PaymentProof)],
        ['query'],
      ),
    'getMyRegistrations' : IDL.Func(
        [],
        [IDL.Vec(TournamentRegistration)],
        ['query'],
      ),
    'getMySupportTickets' : IDL.Func([], [IDL.Vec(SupportTicket)], ['query']),
    'getMyUserId' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getMyWithdrawalRequests' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(WithdrawalRequest)],
        ['query'],
      ),
    'getRegistrationsForTournament' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TournamentRegistration)],
        ['query'],
      ),
    'getSocialLinks' : IDL.Func([], [SocialLinks], ['query']),
    'getTermsAndConditions' : IDL.Func([], [TermsAndConditions], ['query']),
    'getTournamentById' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Tournament)],
        ['query'],
      ),
    'getTournamentsByMap' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Tournament)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserWalletBalance' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getWalletBalance' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'isAdminPrincipal' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markWithdrawalRequestProcessed' : IDL.Func([IDL.Text], [], []),
    'registerAdminPrincipal' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'registerForTournament' : IDL.Func(
        [IDL.Text, IDL.Text, ExternalBlob],
        [IDL.Text],
        [],
      ),
    'registerForTournamentWithCoins' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'registerPlayer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
    'rejectPaymentProof' : IDL.Func([IDL.Text], [], []),
    'rejectWithdrawalRequest' : IDL.Func([IDL.Text], [], []),
    'replyToSupportTicket' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchSupportTicketsByPlayerName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SupportTicket)],
        ['query'],
      ),
    'setDomainName' : IDL.Func([IDL.Text], [], []),
    'submitPaymentProof' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'submitWithdrawalRequest' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Text],
        [],
      ),
    'updateRegistrationStatus' : IDL.Func(
        [IDL.Text, RegistrationStatus],
        [],
        [],
      ),
    'updateSocialLinks' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateTermsAndConditions' : IDL.Func([IDL.Text], [], []),
    'updateTournamentQrCode' : IDL.Func([IDL.Text, ExternalBlob], [], []),
    'updateTournamentRoomDetails' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateTournamentStatus' : IDL.Func([IDL.Text, TournamentStatus], [], []),
    'verifyOtp' : IDL.Func([IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };