/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface PaymentProof {
  'transactionRef' : string,
  'status' : PaymentProofStatus,
  'userId' : string,
  'imageBase64' : string,
  'timestamp' : Time,
  'amount' : bigint,
  'proofId' : string,
}
export type PaymentProofStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Player {
  'principal' : Principal,
  'displayName' : string,
  'bgmiPlayerId' : string,
  'mobile' : string,
}
export type RegistrationStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface SocialLinks {
  'instagram' : string,
  'youtube' : string,
  'telegram' : string,
}
export interface SupportTicket {
  'status' : TicketStatus,
  'adminReply' : [] | [string],
  'subject' : string,
  'playerId' : string,
  'createdAt' : Time,
  'description' : string,
  'ticketId' : string,
  'repliedAt' : [] | [Time],
  'playerName' : string,
  'screenshotBlob' : [] | [ExternalBlob],
}
export interface TermsAndConditions { 'content' : string }
export type TicketStatus = { 'closed' : null } |
  { 'open' : null } |
  { 'replied' : null };
export type Time = bigint;
export interface Tournament {
  'id' : string,
  'map' : string,
  'status' : TournamentStatus,
  'qrCodeBlob' : [] | [ExternalBlob],
  'name' : string,
  'roomPassword' : [] | [string],
  'totalSlots' : bigint,
  'upiId' : string,
  'entryFee' : bigint,
  'roomId' : [] | [string],
  'filledSlots' : bigint,
  'dateTime' : Time,
  'matchRules' : string,
  'prizePool' : bigint,
}
export interface TournamentRegistration {
  'status' : RegistrationStatus,
  'paymentScreenshotBlob' : ExternalBlob,
  'playerId' : string,
  'registrationId' : string,
  'tournamentId' : string,
}
export type TournamentStatus = { 'closed' : null } |
  { 'upcoming' : null } |
  { 'completed' : null } |
  { 'ongoing' : null };
export interface UserProfile {
  'displayName' : string,
  'bgmiPlayerId' : string,
  'mobile' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VerifiedUserProfile {
  'id' : string,
  'coinWallet' : bigint,
  'displayName' : string,
  'bgmiPlayerId' : string,
  'mobile' : string,
}
export interface WithdrawalRequest {
  'status' : WithdrawalStatus,
  'requestId' : string,
  'userId' : string,
  'timestamp' : Time,
  'upiId' : string,
  'amount' : bigint,
}
export type WithdrawalStatus = { 'pending' : null } |
  { 'rejected' : null } |
  { 'processed' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCoins' : ActorMethod<[string, bigint], undefined>,
  'addPrizeCoins' : ActorMethod<[string, bigint], undefined>,
  'approvePaymentProof' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'closeSupportTicket' : ActorMethod<[string], undefined>,
  'createSupportTicket' : ActorMethod<
    [string, string, string, [] | [ExternalBlob]],
    string
  >,
  'createTournament' : ActorMethod<
    [string, Time, bigint, bigint, string, bigint, string, string],
    string
  >,
  'deductCoins' : ActorMethod<[string, bigint], undefined>,
  'distributePrizeCoins' : ActorMethod<[string, string, bigint], undefined>,
  'findUnusedSlots' : ActorMethod<[], Array<Tournament>>,
  'generateOtp' : ActorMethod<[], string>,
  'getAdminPrincipal' : ActorMethod<[], [] | [Principal]>,
  'getAllPaymentProofs' : ActorMethod<[], Array<PaymentProof>>,
  'getAllPlayers' : ActorMethod<[], Array<Player>>,
  'getAllSupportTicketsSorted' : ActorMethod<[], Array<SupportTicket>>,
  'getAllTournaments' : ActorMethod<[], Array<Tournament>>,
  'getAllVerifiedUsers' : ActorMethod<[], Array<VerifiedUserProfile>>,
  'getAllWithdrawalRequests' : ActorMethod<[], Array<WithdrawalRequest>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDomainName' : ActorMethod<[], string>,
  'getMyPaymentProofs' : ActorMethod<[string], Array<PaymentProof>>,
  'getMyRegistrations' : ActorMethod<[], Array<TournamentRegistration>>,
  'getMySupportTickets' : ActorMethod<[], Array<SupportTicket>>,
  'getMyUserId' : ActorMethod<[], [] | [string]>,
  'getMyWithdrawalRequests' : ActorMethod<[string], Array<WithdrawalRequest>>,
  'getRegistrationsForTournament' : ActorMethod<
    [string],
    Array<TournamentRegistration>
  >,
  'getSocialLinks' : ActorMethod<[], SocialLinks>,
  'getTermsAndConditions' : ActorMethod<[], TermsAndConditions>,
  'getTournamentById' : ActorMethod<[string], [] | [Tournament]>,
  'getTournamentsByMap' : ActorMethod<[string], Array<Tournament>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserWalletBalance' : ActorMethod<[string], bigint>,
  'getWalletBalance' : ActorMethod<[string], bigint>,
  'isAdminPrincipal' : ActorMethod<[Principal], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markWithdrawalRequestProcessed' : ActorMethod<[string], undefined>,
  'registerAdminPrincipal' : ActorMethod<[Principal], boolean>,
  'registerForTournament' : ActorMethod<[string, string, ExternalBlob], string>,
  'registerForTournamentWithCoins' : ActorMethod<[string, string], string>,
  'registerPlayer' : ActorMethod<[string, string, string], string>,
  'rejectPaymentProof' : ActorMethod<[string], undefined>,
  'rejectWithdrawalRequest' : ActorMethod<[string], undefined>,
  'replyToSupportTicket' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchSupportTicketsByPlayerName' : ActorMethod<
    [string],
    Array<SupportTicket>
  >,
  'setDomainName' : ActorMethod<[string], undefined>,
  'submitPaymentProof' : ActorMethod<[string, bigint, string, string], string>,
  'submitWithdrawalRequest' : ActorMethod<[string, bigint, string], string>,
  'updateRegistrationStatus' : ActorMethod<
    [string, RegistrationStatus],
    undefined
  >,
  'updateSocialLinks' : ActorMethod<[string, string, string], undefined>,
  'updateTermsAndConditions' : ActorMethod<[string], undefined>,
  'updateTournamentQrCode' : ActorMethod<[string, ExternalBlob], undefined>,
  'updateTournamentRoomDetails' : ActorMethod<
    [string, string, string],
    undefined
  >,
  'updateTournamentStatus' : ActorMethod<[string, TournamentStatus], undefined>,
  'verifyOtp' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];